export const resourceList = [
    {
        id:"1",
        city : "Bengaluru", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"2",
        city : "Bengaluru", 
        resourceName : "bed availability",
        hospitalName : "Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"3",
        city : "Bengaluru", 
        resourceName : "bed availability",
        hospitalName : "Life Savior Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
     {
        id:"4",
        city : "Bengaluru", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"5",
        city : "Chennai", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"6",
        city : "Delhi", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"7",
        city : "Chennai", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"8",
        city : "Chennai", 
        resourceName : "bed availability",
        hospitalName : "Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"9",
        city : "Delhi", 
        resourceName : "bed availability",
        hospitalName : "Life Savior Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
     {
        id:"10",
        city : "Hyderabad", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"11",
        city : "Hyderabad", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    },
    {
        id:"12",
        city : "Delhi", 
        resourceName : "bed availability",
        hospitalName : "Save Life Hospital",
        address: "123, Alpha Street, Health City",
        phone : "123-456-7890",
        normalBedsTotal : "20",
        normalBedsAvailable : "10",
        oxygenBedsTotal : "10",
        oxygenBedsAvailable: "2",
        icuBedsTotal : "5",
        icuBedsAvailable : "1",
        icuBedsWithVentilatorTotal : "2",
        icuBedsWithVentilatorAvailable : "0" 
    }

]

